apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-frontend
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - image: todo-frontend:latest
        name: todo-frontend
        ports:
        - containerPort: 3000
        resources: {}
status: {}
