apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-backend
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - image: todo-backend:latest
        name: todo-backend
        imagePullPolicy: Never
        command: ["python"]
        args: ["-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000